### ISSUE TITLE
error 500 on index.ws

### ISSUE THREAD

**Issue by yalh76** [YunoHost/yunorunner#3]
I've installed two times yunnorunner on fresh install Debian + Yunohost + CI_package_check (+build_CI.sh) + yunorunner_ynh_core from @maniackcrudelis .

CI_package_check is working fine.

Yunnorunner works also: 
![capture](https://user-images.githubusercontent.com/30271971/52698441-c4bd5e00-2f73-11e9-960c-727fbcd6f062.PNG)

But I have an error on the webinterface:
![capture](https://user-images.githubusercontent.com/30271971/52698687-51681c00-2f74-11e9-9d36-1de39e678833.PNG)

And here are the journalctl -u yunorunner:
![capture](https://user-images.githubusercontent.com/30271971/52698786-87a59b80-2f74-11e9-89e6-779cd881b0a7.PNG)

I don't know if it's related to `add the magical lines to allow websocket (it's not allowed for whatever reason)` from the readme..

But port 4242 is opened on the firewall: 
![image](https://user-images.githubusercontent.com/30271971/52698929-e23ef780-2f74-11e9-9756-165bb8e533c1.png)

PS: my yunorunner is only available from internet using IPV6 ...

**Comment by Psycojoker** [comment]
Looking at your error that really seems like an error in @maniackcrudelis package regarding SSOWat configuration :/

You'll probably want to reopen this bug on the package repository as I can't really do anything about that, sorry :x https://github.com/YunoHost-Apps/yunorunner_ynh_core

**Comment by yalh76** [comment]
Well, I've tested stoping nginx  and directly adding a port forwarding with SSH and I have the same result...
I will try to install it from scratch, manually on a debian without yunohost, and let you know if it works

Do you what are the magical lines to allow websocket ? (as written in the deployment part of the readme)

**Comment by yalh76** [comment]
I find the problem ^^
On a fresh debian only install
When installing the requirements: `ve3/bin/pip install -r requirements.txt`
I had the error: "sanic 18.12.0 has requirement websockets<7.0,>=6.0, but you'll have websockets 5.0.1 which is incompatible."

So I had to do:
```
ve3/bin/pip uninstall websockets


ve3/bin/pip  install 'websockets>=6.0,<7.0'
```
And now it's working, also on https://github.com/YunoHost-Apps/yunorunner_ynh_core
I don't know how to fix the requirements.txt... I don't know python ://

**Comment by yalh76** [comment]
PS: doing some tests, I've seen some errors:

1. `ve3/bin/python ./run.py /path/to/analyseCI.sh -d` -d argument is not available
2. for the argument `--dont-minotor-apps-list` maybe there is a spelling error ;) not `minotor `but `monitor`
![capture](https://user-images.githubusercontent.com/30271971/52806785-312a8100-308a-11e9-964d-8c7323a21183.PNG)
