### ISSUE TITLE
Job still running when asked to stop or restart.

### ISSUE THREAD

**Issue by kay0u** [YunoHost/yunorunner#6]
When I click on the button **Cancel Job** or **Restart Job**, the job is still running in background.

To stop a job, yunorunner must stop the script [analyseCI.sh](https://github.com/YunoHost/CI_package_check/blob/master/analyseCI.sh)

**Comment by Psycojoker** [comment]
I need information on how to gracely stop analyseCI.sh whithout conflicting if there are several instances running next to each other to do that :x  

Do you have this information?

**Comment by maniackcrudelis** [comment]
You run analyseCI.sh by calling it from YunoRunner. When the script start, it prints its own PID into a file.
This file is checked by pcheckCI.sh to know if the script is still running.

If YunoRunner stop the execution of the script, so just by killing the process that call the script. pcheckCI.sh will detect that no script is running anymore with this PID. So it will stop the test.

**Comment by Psycojoker** [comment]
This is actually what should already happen normally '-' 

https://github.com/YunoHost/yunorunner/blob/master/run.py#L823

https://github.com/YunoHost/yunorunner/blob/master/run.py#L442

**Comment by Psycojoker** [comment]
I'm guess I'm closing this one since there is not more feedback on it, don't hesitate to reopen :)

**Comment by MayeulC** [comment]
I cancelled that job: https://ci-apps-dev.yunohost.org/ci/job/3983 when I realized I should rebase again before testing.

However I cannot launch a new test: https://ci-apps-dev.yunohost.org/ci/job/3984

> !!! Another analyseCI process is currently using the lock ./CI-1.lock !!!

I'm guessing it has to do with that issue?
